# Generated by Django 6.1 on 2026-08-13 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mood', models.CharField(choices=[('peace', 'Peace'), ('energy', 'Energy'), ('wonder', 'Wonder'), ('reset', 'Reset')], max_length=10)),
                ('crowd_preference', models.CharField(choices=[('quiet', 'Somewhere quiet'), ('social', 'Around people')], max_length=10)),
                ('distance', models.CharField(choices=[('walkable', 'Walkable'), ('under_1hr', 'Under 1 hour'), ('day_trip', 'Day trip')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'mood queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('going', "I'm going"), ('declined', 'Not this time'), ('skipped', 'Show another')], max_length=10)),
                ('decline_reason', models.CharField(blank=True, choices=[('wrong_mood', 'Wrong mood'), ('too_far', 'Too far'), ('not_safe', "Doesn't feel safe"), ('been_there', 'Already been'), ('bad_timing', 'Bad timing'), ('other', 'Other')], max_length=15)),
                ('decline_note', models.CharField(blank=True, max_length=200)),
                ('visited', models.BooleanField(null=True)),
                ('visit_mood_match', models.PositiveSmallIntegerField(blank=True, help_text='1-5: did it deliver the feeling she wanted?', null=True)),
                ('visit_safety_score', models.PositiveSmallIntegerField(blank=True, help_text='1-5: how safe did she feel?', null=True)),
                ('visit_note', models.TextField(blank=True)),
                ('would_recommend', models.BooleanField(null=True)),
                ('share_review', models.BooleanField(default=False, help_text='Did she opt to share her note anonymously with other women?')),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_responses', to='experiences.experience')),
                ('mood_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='moods.moodquery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recommended_at'],
            },
        ),
    ]
