# Generated by Django 6.1 on 2026-08-13 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('vibe_tags', models.JSONField(default=list, help_text='e.g. ["peaceful", "contemplative"]')),
                ('solo_difficulty', models.PositiveSmallIntegerField(default=3, help_text='1=very easy alone, 5=challenging solo')),
                ('min_comfort_tier', models.CharField(choices=[('first_timer', 'First timer ok'), ('cautious', 'Cautious minimum'), ('confident', 'Confident only')], default='first_timer', max_length=15)),
                ('budget_tier', models.CharField(choices=[('free', 'Free'), ('under_500', 'Under Rs 500'), ('under_1000', 'Under Rs 1000'), ('above_1000', 'Above Rs 1000')], default='free', max_length=10)),
                ('best_months', models.JSONField(blank=True, default=list, help_text='BS month numbers')),
                ('total_visitors', models.PositiveIntegerField(default=0)),
                ('felt_safe_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyIntel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('accommodation', 'Accommodation'), ('area_safety', 'Area at night'), ('connectivity', 'Connectivity'), ('local_attitude', 'Local attitude'), ('emergency', 'Emergencies'), ('return_route', 'Getting back')], max_length=20)),
                ('content', models.TextField()),
                ('safe_until', models.TimeField(blank=True, help_text='Last comfortable time to be here', null=True)),
                ('transport_back', models.CharField(blank=True, help_text='How to get back + cutoff time', max_length=200)),
                ('source_type', models.CharField(choices=[('founder_verified', 'Founder verified'), ('community', 'Community report'), ('partner', 'Partner verified')], default='founder_verified', max_length=20)),
                ('verified_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_intel', to='experiences.experience')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stay_type', models.CharField(choices=[('homestay', 'Homestay'), ('hotel', 'Hotel'), ('cafe', 'Café'), ('restaurant', 'Restaurant')], max_length=15)),
                ('price_range', models.CharField(blank=True, max_length=30)),
                ('verification_note', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_stays', to='experiences.experience')),
            ],
        ),
        migrations.CreateModel(
            name='VibeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_type', models.CharField(choices=[('weekday', 'Weekday'), ('weekend', 'Weekend'), ('any', 'Any day')], max_length=10)),
                ('time_start', models.TimeField(help_text='e.g. 16:00')),
                ('time_end', models.TimeField(help_text='e.g. 19:00')),
                ('crowd_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('vibe_notes', models.CharField(blank=True, max_length=200)),
                ('solo_comfortable', models.BooleanField(default=True, help_text='Can a woman sit alone here without stares?')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibe_windows', to='experiences.experience')),
            ],
            options={
                'ordering': ['day_type', 'time_start'],
            },
        ),
    ]
