# Generated by Django 6.1 on 2026-08-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='scene_type',
            field=models.CharField(choices=[('mainstream', 'Mainstream landmark'), ('hidden_gem', 'Hidden gem'), ('cafe_social', 'Café & social')], default='hidden_gem', max_length=15),
        ),
    ]
