# Generated by Django 6.1 on 2026-09-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experience_scene_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedstay',
            name='price_range',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
